### ISSUE TITLE
For joint filing withholding / medicare_withheld / state_withholding should be list

### ISSUE THREAD

**Issue by yangchenyun** [davidcmoore/python-taxes#1]
For a joint filing, the wages expect a list but the withholding parts expect a single float; if multiple w2 is expected, the input fields of withholding should be list as well.

**Comment by davidcmoore** [comment]
Hi Steven,

I've split the wages part into a list of length 2 because some forms
require the spouse-versus-taxpayer wages to be input separately. Keep in
mind the list is not for each W-2 form, but for each spouse.

For withholding, it's not an array, but you can make your inputs pretty by
doing something like this:

inputs = {
   'wages': [ spouse1, spouse2 ],
   'withholding': sum([ val1, val2 ]),
   ...
}

Thanks,
David
